"""Standalone helpers for the Hermes Agent goal-prompt-generator skill."""

from .core import (
    AUTONOMY,
    CLAUDE_CLI_EXECUTION_CONTRACT,
    CLAUDE_CLI_REQUIRED_FLAGS,
    SOFTWARE_CONSTRAINTS,
    SOFTWARE_ENGINEERING_PRINCIPLES,
    SOFTWARE_CLEANUP_REQUIREMENT,
    VERSION,
    PreparedGoal,
    ValidationResult,
    build_optimized_markdown,
    build_task_list,
    classify_domain,
    handoff_prompt,
    parse_metadata,
    prepare_goal_prompt,
    stable_hash,
    task_list_path,
    validate_optimized_markdown,
    write_task_list,
)

__all__ = [
    "AUTONOMY",
    "CLAUDE_CLI_EXECUTION_CONTRACT",
    "CLAUDE_CLI_REQUIRED_FLAGS",
    "SOFTWARE_CONSTRAINTS",
    "SOFTWARE_CLEANUP_REQUIREMENT",
    "SOFTWARE_ENGINEERING_PRINCIPLES",
    "VERSION",
    "PreparedGoal",
    "ValidationResult",
    "build_optimized_markdown",
    "build_task_list",
    "classify_domain",
    "handoff_prompt",
    "parse_metadata",
    "prepare_goal_prompt",
    "stable_hash",
    "task_list_path",
    "validate_optimized_markdown",
    "write_task_list",
]
